server:
  port: 9082
  tomcat:
    threads:
      max: 2
      min-spare: 1
spring:
  application:
    name: quemsi-agent
  security:
    oauth2:
      client:
        registration:
          api-client:
            provider: keycloak
            client-id: ${CLIENT-ID}
            client-name: ${CLIENT-ID}
            client-secret: ${CLIENT-SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://127.0.0.1/idm/realms/quemsi/protocol/openid-connect/token
oauth2:
  registration:
    id: api-client              
resource:
  base: http://127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"
mysqlbackup:
  temp-dir: tmp
api:
  retry: 5 
logging:
  level:
    root: INFO
    com.givlon.indexer.service: INFO
