server:
  port: 9082
  tomcat:
    threads:
      max: 2
      min-spare: 1
spring:
  application:
    name: quemsi-agent
    version: '@project.version@'
      
oauth2:
  registration:
    id: api-client              
management:
  endpoints:
    web:
      exposure:
        include: "*"
mysqlbackup:
  temp-dir: tmp
quemsi-api:
  server-url: https://quemsi.com
  keycloak-url: https://quemsi.com
  realm: quemsi
  client-id: ${CLIENT-ID}
  client-secret: ${CLIENT-SECRET}
  log-request-detail: true
  retry: 5
logging:
  level:
    root: INFO
    com.givlon.indexer.service: INFO
