server:
  port: 9082
  tomcat:
    threads:
      max: 2
      min-spare: 1
spring:
  application:
    name: quemsi-agent
      
oauth2:
  registration:
    id: api-client              
resource:
  base: http://127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"
mysqlbackup:
  temp-dir: tmp
quemsi-api:
  server-url: http://127.0.0.1
  token-uri: http://127.0.0.1/idm/realms/quemsi/protocol/openid-connect/token
  realm: quemsi
  client-id: ${CLIENT-ID}
  client-secret: ${CLIENT-SECRET}
  log-request-detail: true
  retry: 5
logging:
  level:
    root: INFO
    com.givlon.indexer.service: INFO
