Args = -H:ClassInitialization=org.springframework.http.codec.xml.XmlEventDecoder:rerun \
  -H:ClassInitialization=org.springframework.util.xml.StaxUtils:rerun \
  -H:ClassInitialization=org.springframework.util.ClassUtils:rerun \
  -H:ClassInitialization=org.springframework.util.ConcurrentReferenceHashMap:rerun \
  -H:ClassInitialization=javax.xml.stream.XMLInputFactory:rerun \
  -H:ClassInitialization=javax.xml.stream.FactoryFinder:rerun \
  -H:ClassInitialization=org.codehaus.stax2.XMLInputFactory2:rerun \
  -H:ClassInitialization=com.ctc.wstx.stax.WstxInputFactory:rerun \
  -H:ClassInitialization=com.ctc.wstx.api.CommonConfig:rerun \
  -H:ClassInitialization=com.ctc.wstx.api.ReaderConfig:rerun \
  -H:ClassInitialization=com.ctc.wstx.util.DefaultXmlSymbolTable:rerun \
  --initialize-at-build-time=org.apache.commons.logging.LogFactory,org.slf4j.helpers.Reporter,org.apache.commons.logging.LogFactoryService,org.apache.commons.logging.impl.LogFactoryImpl,org.apache.commons.logging.impl.SimpleLog,org.apache.commons.logging.impl.NoOpLog,org.apache.commons.logging.impl.Jdk14Logger,org.apache.commons.logging.impl.Log4JLogger,org.apache.commons.logging.impl.LogKitLogger

